### ISSUE TITLE
undefined context.output

### ISSUE THREAD

**Issue by jcferrer** [apigee-127/bagpipes#10]
I am trying to use the geocoding example shown in the documentation. Geocoding works fine, but I cannot find a way to get the final results from the context.output property. It seems to be undefined.
I can see it in the debug output, but `console.log(context.output)` returns undefined.

config/default.yaml

```
#1. Define a http callout we'll use in our pipe
 google_geocode:
   name: http
   input:
     url: http://maps.googleapis.com/maps/api/geocode/json?sensor=true  
     params:
       address: .request.parameters.address.value[0]

 #2. Defined the pipe flow we'll play
 getAddressLocation:
   - google_geocode            # call the fitting defined in this swagger
   - path: body                # system fitting: get body from output
   - parse: json               # body is a json string, parse to object
   - path: results             # get results from body
   - first                     # get first result
   - path: geometry.location   # output = { lat: n, lng: n }
```

app.js

```
'use strict';

var fs = require('fs');
var bagpipes = require('bagpipes');
var yaml = require('js-yaml');

var pipesDefs = yaml.safeLoad(fs.readFileSync('config/default.yaml'));
var pipesConfig = {};
var pipes = bagpipes.create(pipesDefs, pipesConfig);
var pipe = pipes.getPipe('getAddressLocation');

var context = {
    request: { 
        parameters: { 
            address: { 
                value: [ 'Frisco TX. 75034' ]
            }
        }
    }
};
pipes.play(pipe, context);

console.log(context.output);
```
