### ISSUE TITLE
Feature Request: finding pipes by guaranteed and documented order of operations

### ISSUE THREAD

**Issue by osher** [apigee-127/bagpipes#22]
the current way forces us to "rename" a pipe in order to pass fittings-config to it.
e.g.
```
bagpipes:
  my-customized-fitting:
    name:   my-fitting
    custom: setting1
    tuned:  value
  
  my-pipe:
    - my-customized-fitting
```

Why couldn't it be just:

```
bagpipes:
  my-fitting:
    custom: setting
    tuned:  value

  my-pipe:
    - my-fitting
```
