### ISSUE TITLE
Feature Request: "hoisting" of fittings definitions

### ISSUE THREAD

**Issue by osher** [apigee-127/bagpipes#23]
## User Story
**As** a user who wants to manage flow with bagpipes
**I want** to be able to put pipe definition on top of the file and fitting config bellow
**So that** I can hold the important parts on top, and the implementation details bellow

## More info
Current implementation won't recognize fittings that are yet to be loaded but defined bellow.
That makes the bagpipes list start with the petty details instead of the important story.

e.g. the following does not work, and I very much like it to
```
bagpipes:
   my-pipe: 
     - fitting1
     - fitting2

   fitting1: 
      name: my-fitting1
      config: value
   
   fitting2:
      name: my-fitting2
      config: value
```
