### ISSUE TITLE
Bug: fitting input as object with a key with the value 'false' - is lost - kept as `undefined`

### ISSUE THREAD

**Issue by royrothman** [apigee-127/bagpipes#29]
Consider this:
```
bagpipes:
   some-flow:
    - some-fitting:
         key: false
```

When I play the pipe - I get the `false`  of the `ctx.input` as `undefined` :cry: 

bug reproduction:
```
const bagpipes = require('bagpipes');
const pipes = bagpipes.create({ 'foo' : [ { emit: { bar: false } } ] } );
pipes.play( pipes.getPipe( 'foo' ) , ctx = {} );

if( ctx.output.bar !== false) throw new Error('oups. expected false, but got something else');
```

Thanks
